name: runn test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        run: docker-compose -f docker-compose.yml up -d

      - name: Check Docker status
        run: docker-compose ps

      - name: Wait for 3 seconds
        run: sleep 3

      - name: Runn test
        run: docker-compose exec -it app runn run runn-test.yml
      
      - name: Clean up
        if: always()
        run: docker-compose -f docker-compose.yml down
